### ISSUE TITLE
Publish Test Results in a YAML pipline doesn't work when test fails

### ISSUE THREAD

**Issue by olaj** [Microsoft/vstest#1848]
## Description
While following the tutorial here https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml me and another user noticed that failed tests you get no test results. I've worked around the issue by adding 

**exit 0** after the **RUN dotnet test MyProject.Tests.csproj -c Release --logger "trx;LogFileName=testresults.trx"**

But this isn't perfect since the actual build is passing even though a test failed. I'm not sure this is a bug or just excepted behavior but i think the documentation probably need an update since it doesn't behave in a way i think most people want it to behave.

Original report on the docs: https://github.com/MicrosoftDocs/vsts-docs/issues/2183

I still think it's more related to the docs than vstest but i was told to post it here so.

## Steps to reproduce
Follow this tutorial https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml

## Expected behavior
It should post the test result no matter if the test fails or not. Preferably also fail the build.

## Actual behavior
No test result is posted if the build fail.

**Comment by karanjitsingh** [comment]
@olaj, there's a slight caveat, since all tasks will run even if there is script failure, if this breaks your expected behavior. You can use conditional publish test results

```yml
# Build Docker image for this app, to be published to Docker Registry
pool:
  vmImage: 'ubuntu-16.04'
variables:
  buildConfiguration: 'Release'
steps:
- script: |
    docker build -f Dockerfile.build -t $(dockerId)/dotnetcore-build:$BUILD_BUILDID .
    docker run --name dotnetcoreapp --rm -d $(dockerId)/dotnetcore-build:$BUILD_BUILDID
    docker cp dotnetcoreapp:app/dotnetcore-tests/TestResults $(System.DefaultWorkingDirectory)
    docker cp dotnetcoreapp:app/dotnetcore-sample/out $(System.DefaultWorkingDirectory)
    docker stop dotnetcoreapp
  failOnStderr: true

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  condition: succeededOrFailed()

- script: |
    docker build -f Dockerfile -t $(dockerId)/dotnetcore-sample:$BUILD_BUILDID .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/dotnetcore-sample:$BUILD_BUILDID

  env:
    pswd: $(dockerPassword)

```

This will publish your tests even when the script has failed.
