### ISSUE TITLE
Coverage report file duplicated when using --logger option

### ISSUE THREAD

**Issue by tremblaysimon** [microsoft/vstest#2334]
Please see the reported issue here https://github.com/tonerdo/coverlet/issues/733 about using --logger option in conjunction with --collect:"XPlat Code Coverage". 

We think that it should be related more with vstest than coverlet. 

Is it an expected behavior to get two generated code coverage file instead of one if we use vstest logger option?

**Comment by nohwnd** [comment]
@jakubch1 this is CC related, please have a look 🙂

**Comment by nohwnd** [comment]
Or maybe @MarcoRossignoli if this is coverlet related? Thx

**Comment by MarcoRossignoli** [comment]
I dont' think it's related to coverlet, collectors(wrote by @vagisha-nidhi) only send artifact through data sink https://github.com/tonerdo/coverlet/blob/master/src/coverlet.collector/DataCollection/AttachmentManager.cs#L146

We don't handle nothing about loggers.

**Comment by DotNetSparky** [comment]
I'm experiencing the same thing (also using coverlet)... each xml file is duplicated.

**Comment by Sebbl22** [comment]
Same here.
tests.runsettings:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<RunSettings>
    <RunConfiguration>
        <ResultsDirectory>.\TestResults</ResultsDirectory>
    </RunConfiguration>
    <DataCollectionRunSettings>
        <DataCollectors>
            <DataCollector friendlyName="XPlat code coverage">
                <Configuration>
                    <Format>cobertura</Format>
                    <IncludeTestAssembly>false</IncludeTestAssembly>
                </Configuration>
            </DataCollector>
        </DataCollectors>
    </DataCollectionRunSettings>
    <LoggerRunSettings>
        <Loggers>
            <Logger friendlyName="trx" />
        </Loggers>
    </LoggerRunSettings>
</RunSettings>
```
`dotnet test --settings tests.runsettings`

Result:
![grafik](https://user-images.githubusercontent.com/10319545/79432207-ccd7ba00-7fcb-11ea-93ba-fe31a4a8659e.png)
I have four projects and every coverage.cobertura.xml-file is duplicated.

**Comment by manishi2V** [comment]
Is there any solution found for this issue?

**Comment by danjcosg** [comment]
Still experiencing this

**Comment by gioce90** [comment]
I noticed the same if I use a . runsettings configuration file. But if I use the argument directly in an Azure Pipeline task:

```
- task: DotNetCoreCLI@2
    displayName: 'DotNetCoreCLI Test with report (cobertura format)'
    inputs:
      command: test
      projects: '**/**.Tests.csproj'
      arguments: '--no-restore --collect "Code Coverage" --logger trx --results-directory "TestResults/Coverage/" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
      publishTestResults: false
```

The problem just disappear 

(This works also locally. The problem is the logger in the in the . runsettings)

**Comment by celluj34** [comment]
I'm having the same problem with `--collect:"XPlat Code Coverage"`.

**Comment by bitbonk** [comment]
I have the same problem with a pretty basic command:

> dotnet test C:\source\repos\MyProject\MyProject.sln --collect "XPlat Code Coverage" --logger trx --no-build --no-restore --results-directory C:\source\repos\MyProject\artifacts\tests\results

**Comment by bitbonk** [comment]
@nohwnd @MarcoRossignoli What can we do about it?

**Comment by gioce90** [comment]
This issue is still open after more than one year....

**Comment by MarcoRossignoli** [comment]
The behavior is expected, trx logger currently creates a file and a directory like:

TestResult/userName_machineName_timespan<- folder
TestResult/trxfilename.trx

all attachments generated by the test session are copied inside the `userName_machineName_timespan` directory and used by the result summary inside Visual Studio when the trx file is open.

For this reason at the end of the test inside the subdirectories of `TestResult` we can find same "attachment" more than one time.

If you need to publish coverage report using `PublishCodeCoverageResults@1` inside Azure DevOps you can try with

```
- task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: .../TestResults/*/*.xml
```

If the issue affect also other scenarios one possible solution could be add a new parameter to the logger like `--logger:"trx;CleanupAttachmentArtifacts=true"` and remove the artifacts after the moving.
