### ISSUE TITLE
TRX file cannot be correctly located in VsTest 16.7

### ISSUE THREAD

**Issue by aDisplayName** [microsoft/vstest#2512]
## Description
Starting today, the VsTest 16.7.0 is available in Azure DevOps pipeline. We got an error message at the end of the VsTest step that it clamied TRX was not found when publishing the test. 
It appears the VsTest was looking for trx file in ```\agent\_work\_temp\TestResults``` while it was actually saved to ```$(Common.TestResultsDirectory)```

We were using VsTest 16.6.1 with the same pipeline this past Sunday without problem.

Here is the part of our yml pipeline file:
```yml

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'VsTest Platform Installer'
  inputs:
    versionSelector: latestStable

# To avoid vstest execution error, we need to split tests into group by framework version.
- task: VSTest@2
  displayName: 'VsTest - testAssemblies - .Net Framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\MyApp.UnitTest.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: 'toolsInstaller'
    codeCoverageEnabled: true
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/test/UnitTests/MyApp.UnitTest'
    otherConsoleOptions: '/ResultsDirectory:$(Common.TestResultsDirectory)'
```

Here is the log output:
```
**************** Starting test execution *********************
C:\agent\_work\_tool\VsTest\16.7.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\agent\_work\_temp\tb3bjofmr20.tmp"
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe "C:\agent\_work\31\s\test\UnitTests\MyApp.UnitTest\bin\x86\Release\MyApp.UnitTest.dll"
/Settings:"C:\agent\_work\_temp\5k2prh3hdf4.tmp.runsettings"
/Logger:"trx"
/TestAdapterPath:"C:\agent\_work\31\s\test\UnitTests\MyApp.UnitTest"
/ResultsDirectory:C:\agent\_work\31\TestResults
Starting test execution, please wait...
Microsoft (R) Coverage Collection Tool Version 16.0.30319.200


Copyright (c) Microsoft Corporation.  All rights reserved.




Results File: C:\agent\_work\31\TestResults\CMMMM038$_CMMMM038_2020-08-07_14_38_13.trx
Attachments:
  C:\agent\_work\31\TestResults\c52bfe34-15a7-4762-bbff-fbba29cac278\CMMMM038$_CMMMM038 2020-08-07 14_38_06.coverage
Test Run Successful.
Total tests: 5
     Passed: 5
 Total time: 9.0765 Seconds
Vstest.console.exe exited with code 0.
**************** Completed test execution *********************
Test results files: 
##[error]Error occurred while publishing test results : MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory C:\agent\_work\_temp\TestResults.
##[error]Skipping marking test run as complete as test run id 0 is invalid.
Completed TestExecution Model...
##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
##[error]Error: The process 'C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1
##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
Finishing: VsTest - testAssemblies - .Net Framework

```

Here is the log output for VsTest 16.7.0 installation
```
==============================================================================
Task         : Visual Studio test platform installer
Description  : Acquire the test platform from nuget.org or the tool cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
Version      : 1.151.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer
==============================================================================
Starting VsTest platform tools installer task.
==============================================================================
Looking for the latest stable version of the Microsoft.Testplatform.
C:\agent\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.151.3\nuget.exe list packageid:Microsoft.TestPlatform -NonInteractive -Source https://api.nuget.org/v3/index.json
Microsoft.TestPlatform 16.7.0
C:\agent\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.151.3\nuget.exe install Microsoft.TestPlatform -Version 16.7.0 -Source https://api.nuget.org/v3/index.json -OutputDirectory C:\agent\_work\_temp\VsTest -NoCache -DirectDownload -NonInteractive
Feeds used:
  https://api.nuget.org/v3/index.json



Attempting to gather dependency information for package 'Microsoft.TestPlatform.16.7.0' with respect to project 'C:\agent\_work\_temp\VsTest', targeting 'Any,Version=v0.0'
Gathering dependency information took 1.26 sec
Attempting to resolve dependencies for package 'Microsoft.TestPlatform.16.7.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.TestPlatform.16.7.0'
Resolved actions to install package 'Microsoft.TestPlatform.16.7.0'
Retrieving package 'Microsoft.TestPlatform 16.7.0' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.testplatform/16.7.0/microsoft.testplatform.16.7.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.testplatform/16.7.0/microsoft.testplatform.16.7.0.nupkg 51ms
Adding package 'Microsoft.TestPlatform.16.7.0' to folder 'C:\agent\_work\_temp\VsTest'
Added package 'Microsoft.TestPlatform.16.7.0' to folder 'C:\agent\_work\_temp\VsTest'
Successfully installed 'Microsoft.TestPlatform 16.7.0' to C:\agent\_work\_temp\VsTest
Executing nuget actions took 7.53 sec
Caching tool: VsTest 16.7.0 x64
VsTest will use the Test Platform package found in C:\agent\_work\_tool\VsTest\16.7.0\x64
```

We were using VsTest 16.6.1 without problem before today.

## Environment
The agent is running at Windows 10 1803

**Comment by Sanan07** [comment]
@aDisplayName Are you able to access this result file `Results File: C:\agent\_work\31\TestResults\CMMMM038$_CMMMM038_2020-08-07_14_38_13.trx`? As I know ,we have not done any changes related to TestResults directory in 16.7.0. We will try to look into it.

**Comment by Sanan07** [comment]
@aDisplayName I tested using VsTest 16.7.0 with specifying `ResultsDirectory` and it worked fine.

![trx](https://user-images.githubusercontent.com/8465726/89643970-32bbba80-d8b7-11ea-9e21-b984de4a59d8.PNG)

So, in your case trx file was saved to `/ResultsDirectory:C:\agent\_work\31\TestResults` as you specify it as argument, but AzDo were looking at it in `$(Common.TestResultsDirectory)` which has value `C:\agent\_work\_temp\TestResults`, that why it failed to find it there.

And this `MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory` looks like a AzDo exception. Maybe @ShreyasRmsft can also help us.

@aDisplayName  Could you also provide runsettings file?

**Comment by aDisplayName** [comment]
Thanks @Sanan07 

> @aDisplayName Are you able to access this result file `Results File: C:\agent\_work\31\TestResults\CMMMM038$_CMMMM038_2020-08-07_14_38_13.trx`? As I know ,we have not done any changes related to TestResults directory in 16.7.0. We will try to look into it.

Yes, the trx, coverage, and the raw data were all under C:\agent\_work\31 folder.
There is nonthing under C:\agent\_work\_temp\TestResults folder.


> @aDisplayName I tested using VsTest 16.7.0 with specifying `ResultsDirectory` and it worked fine.
> 
> ![trx](https://user-images.githubusercontent.com/8465726/89643970-32bbba80-d8b7-11ea-9e21-b984de4a59d8.PNG)
> 
> So, in your case trx file was saved to `/ResultsDirectory:C:\agent\_work\31\TestResults` as you specify it as argument, but AzDo were looking at it in `$(Common.TestResultsDirectory)` which has value `C:\agent\_work\_temp\TestResults`, that why it failed to find it there.
> 
> And this `MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory` looks like a AzDo exception. Maybe @ShreyasRmsft can also help us.
> 
> @aDisplayName Could you also provide runsettings file?

The only runsettings was the one generated by VsTest task. I've attached the full log here.
[21.log](https://github.com/microsoft/vstest/files/5042082/21.log)

Also, the azure agent version is 2.165.0

**Comment by aDisplayName** [comment]
@Sanan07 , I agree with you. It seems VsConsole.exe did complete with exit code 0. And indeed it was the DTAExecutionHost.exe which exited with error code 1

**Comment by Sanan07** [comment]
@aDisplayName Please look at this https://github.com/microsoft/azure-pipelines-tasks/issues/11526 and https://developercommunity.visualstudio.com/content/problem/756960/21574modulesdtaexecutionhostexe-failed-with-exit-c.html
As I understood by default AzDo writes results in temp folder, but you can overwrite it. But in your case it still looks at temp folder, instead of looking at the folder which you specify as an argument. Try to run again an agent and see if you get the same behaviour.

**Comment by aDisplayName** [comment]
@Sanan07  But the only thing between pass and fail is the change from VsTest 16.6.1 to 16.7.0. 

Actually I tried with 16.6.1 today after we had problem with 16.7.0, and the tasks passed without any glitch. Back to 16.7.0, failed again. Same build agent.

**Comment by Sanan07** [comment]
@aDisplayName Could you please provide installation logs for VsTest 16.6.1 as you provided in your post for 16.7.0?

As you may see above 16.7.0 was installed inside `work\temp` folder, probably that is why it tries to reach trx log file from there : 

`Adding package 'Microsoft.TestPlatform.16.7.0' to folder 'C:\agent\_work\_temp\VsTest'
Added package 'Microsoft.TestPlatform.16.7.0' to folder 'C:\agent\_work\_temp\VsTest'
Successfully installed 'Microsoft.TestPlatform 16.7.0' to C:\agent\_work\_temp\VsTest
Executing nuget actions took 7.53 sec
Caching tool: VsTest 16.7.0 x64
VsTest will use the Test Platform package found in C:\agent\_work\_tool\VsTest\16.7.0\x64`

**Comment by aDisplayName** [comment]
@Sanan07 as far as I know, every azure task is installed under _work\_temp

**Comment by aDisplayName** [comment]
I am able to reproduce the problem with the following azure pipeline script.
Azure Host Agent: windows-latest
Task Version:
Downloading task: UseDotNet (2.171.0)
Downloading task: PowerShell (2.170.1)
Downloading task: VisualStudioTestPlatformInstaller (1.151.3)
Downloading task: VSTest (2.170.1)
Downloading task: PublishTestResults (2.171.0)


## Using vstest 16.6.1
When using vstest 16.6.1, all task completed without problem
```yml
trigger: none

pool:
  vmImage: 'windows-latest'

workspace:
  clean: all

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.302'
  inputs:
    version: 3.1.302

- powershell: |
    Set-Location $(System.DefaultWorkingDirectory)
    dotnet new mstest -o MyApp.UnitTest
    dotnet build MyApp.UnitTest/MyApp.UnitTest.csproj -o output
  
  
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'VsTest Platform Installer'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'specificVersion'
    testPlatformVersion: '16.6.1'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies - .Net Framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **/MyApp.UnitTest.dll
    searchFolder: '$(System.DefaultWorkingDirectory)/output'
    vsTestVersion: 'toolsInstaller'
    codeCoverageEnabled: true
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/output'
    otherConsoleOptions: '/ResultsDirectory:$(Common.TestResultsDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '$(Common.TestResultsDirectory)/**/*.trx'
```

## Using vstest 16.7.0
When using vstest 16.7.0, the vstest task failed when publishing the test result.
![image](https://user-images.githubusercontent.com/19527258/89701483-f72df880-d969-11ea-9327-e0492b2d1004.png)

```yml
trigger: none

pool:
  vmImage: 'windows-latest'

workspace:
  clean: all

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.302'
  inputs:
    version: 3.1.302

- powershell: |
    Set-Location $(System.DefaultWorkingDirectory)
    dotnet new mstest -o MyApp.UnitTest
    dotnet build MyApp.UnitTest/MyApp.UnitTest.csproj -o output
  
  
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'VsTest Platform Installer'
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'specificVersion'
    testPlatformVersion: '16.7.0'

# To avoid vstest execution error, we need to split tests into group by framework version.
- task: VSTest@2
  displayName: 'VsTest - testAssemblies - .Net Framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **/MyApp.UnitTest.dll
    searchFolder: '$(System.DefaultWorkingDirectory)/output'
    vsTestVersion: 'toolsInstaller'
    codeCoverageEnabled: true
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)/output'
    otherConsoleOptions: '/ResultsDirectory:$(Common.TestResultsDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '$(Common.TestResultsDirectory)/**/*.trx'
```

## Here is the build agent information
```log
2020-08-08T03:14:52.4713503Z ##[section]Starting: Initialize job
2020-08-08T03:14:52.4715025Z Agent name: 'Hosted Agent'
2020-08-08T03:14:52.4715363Z Agent machine name: 'fv-az674'
2020-08-08T03:14:52.4715579Z Current agent version: '2.173.0'
2020-08-08T03:14:52.4767213Z ##[group]Operating System
2020-08-08T03:14:52.4767497Z Microsoft Windows Server 2019
2020-08-08T03:14:52.4767652Z 10.0.17763
2020-08-08T03:14:52.4767782Z Datacenter
2020-08-08T03:14:52.4767933Z ##[endgroup]
2020-08-08T03:14:52.4768088Z ##[group]Virtual Environment
2020-08-08T03:14:52.4768270Z Environment: windows-2019
2020-08-08T03:14:52.4768443Z Version: 20200802.1
2020-08-08T03:14:52.4768749Z Included Software: https://github.com/actions/virtual-environments/blob/win19/20200802.1/images/win/Windows2019-Readme.md
2020-08-08T03:14:52.4769028Z ##[endgroup]
2020-08-08T03:14:52.4769869Z Current image version: '20200802.1'
2020-08-08T03:14:52.4775867Z Agent running as: 'VssAdministrator'
2020-08-08T03:14:52.4815061Z Prepare build directory.
2020-08-08T03:14:52.5078768Z Set build variables.
2020-08-08T03:14:52.5112160Z Download all required tasks.
2020-08-08T03:14:52.5225718Z Downloading task: UseDotNet (2.171.0)
2020-08-08T03:14:54.5404379Z Downloading task: PowerShell (2.170.1)
2020-08-08T03:14:54.8021028Z Downloading task: VisualStudioTestPlatformInstaller (1.151.3)
2020-08-08T03:14:55.1260638Z Downloading task: VSTest (2.170.1)
2020-08-08T03:14:56.7509719Z Downloading task: PublishTestResults (2.171.0)
2020-08-08T03:14:57.5531780Z Checking job knob settings.
2020-08-08T03:14:57.5540533Z    Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
2020-08-08T03:14:57.5541884Z    Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
2020-08-08T03:14:57.5542896Z Finished checking job knob settings.
2020-08-08T03:14:57.5868290Z Start tracking orphan processes.
2020-08-08T03:14:57.5921876Z ##[section]Finishing: Initialize job
```
