### ISSUE TITLE
NuGet package Microsoft.NET.Test.Sdk v16.7.0 no longer works with DotNetCoreCLI@2 for running tests

### ISSUE THREAD

**Issue by DrGriff** [microsoft/vstest#2523]
# Summary of problem
Using Azure Devops, a long established build pipeline failed when running tests after updating the NuGet package Microsoft.NET.Test.Sdk from 16.6.1 to 16.7.0.

The test step as defined in the YAML file was:

```
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
```

[Note: we're also using Sonr to analyse our code.]

The error message was:

> ##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
> "C:\Program Files\dotnet\dotnet.exe" test d:\a\1\s\My.Test.Project\EMy.Test.Project.csproj --logger trx --results-directory d:\a\_temp --configuration Release --collect "Code coverage"

Additional information may be found in this [StackOverflow](https://stackoverflow.com/questions/63309108/azure-devops-tests-failing-when-addressing-multiple-net-frameworks) post.
