### ISSUE TITLE
Get rid of the requirement to manually provision `procdump.exe`

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/vstest#2972]
It is absolutely essential that the ability to collect dumps on test host process crashes can be turned on as simple as possible. It's a huge drain on productivity if every user who wants to do this has to go on a wild goose chase to figure out how to deploy it and add it to the path.

Let's find a way to ensure `procdump.exe` is included in the agent image, and just use that.

**Comment by nohwnd** [comment]
VSTest task carries procdump with it in both yaml and classic pipeline and allows crash dumps to be collected by selecting "" 

![image](https://user-images.githubusercontent.com/5735905/123947754-06160300-d9a1-11eb-9981-2aa5588d054d.png)
![image](https://user-images.githubusercontent.com/5735905/123947873-25ad2b80-d9a1-11eb-96af-6575e0c0c781.png)

(input in yaml: `diagnosticsEnabled: true`)


Debugging issues with setting up procdump can be difficult. When running your pipeline, select to enable diagnostics. The VSTest task will detect this and enable diagnostic run, and upload your logs.
![image](https://user-images.githubusercontent.com/5735905/123948963-4924a600-d9a2-11eb-9883-2713acbc1983.png)

Later you can download them by clicking on your run, and in upper right corner clicking on `...` and selecting Download logs. 

![image](https://user-images.githubusercontent.com/5735905/123949118-812be900-d9a2-11eb-8c23-0ed6d203689d.png)

All our diag logs have extension .diag, and in *datacollector*.diag you will find additional information about what exactly happened.

---

When using `dotnet test` directly for example for testing locally.

On modern frameworks (.NET 5+) you don't need procdump to collect crash dumps, because that ability is built in natively into the runtime. For older frameworks, e.g. .NET Framework 4.7.2 you do need to install procdump. 

To still use dotnet test --blame-crash in azdo, without using the task above you can use chocolatey to install it. It is installing into PATH and we check PATH for procdump.

As you shown in other issue you can install procdump using choco reasonably easy (but make sure to only run it on windows): 

https://github.com/microsoft/vstest/issues/2957#issuecomment-869059872 

```yaml
- powershell: |
    choco install procdump -y
  displayName: Install Procdump
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
```
Or if you prefer checking OS in powershell directly: 

```yaml
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'if ($IsWindows) { choco install procdump -y }'
    pwsh: true
  displayName: 'Install Procdump'
```
