### ISSUE TITLE
VSTest skips running tests when <TargetFramework>net6.0</TargetFramework>

### ISSUE THREAD

**Issue by JohanLarsson** [microsoft/vstest#3191]
```yml
pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: VSTest@2
  inputs:
    configuration: '$(buildConfiguration)'
```

Changing test project to `<TargetFramework>net6.0</TargetFramework>` results in no tests run but still green CI.
This is not a new issue, has been like this for all netcore versions.
