### ISSUE TITLE
Unhelpful warning messages showing up in Azure Pipelines: "Warning: Test Impact (Run only Impacted tests) and Code Coverage data collector will not work."

### ISSUE THREAD

**Issue by kmahone** [microsoft/vstest#3208]
These Warning messages started showing up in our Azure DevOps Pipeline runs:

`Warning: Test Impact (Run only Impacted tests) and Code Coverage data collector will not work.`

We are not trying to use Code Coverage, so these warnings are just noise.

The relevant yml in the Pipeline definition looks like this:

```
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      versionSelector: latestStable

  - task: VSTest@2
    displayName: 'VsTest'
    inputs:
      testAssemblyVer2: '$(testPayloadDir)\Test.*.dll'
      vsTestVersion: toolsInstaller
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      uiTests: true
      rerunFailedTests: true
```
