### ISSUE TITLE
Azure DevOps Release Pipeline - Error Message: get_DataRow .. does not have an implementation

### ISSUE THREAD

**Issue by MartinHatch80** [microsoft/vstest#3238]
## Description

I am getting an error message when trying to execute unit tests using a DevOps RELEASE pipeline. 

```
[MSTest][Discovery][D:\a\r1\a\ExtractedFiles\Framework\MartinHatch.Azure.Functions.v1.Tests.dll] MSTestAdapter failed to discover tests in class 'MartinHatch.Azure.Functions.v1.Tests.TextExtract_IntegrationTests' of assembly 'D:\a\r1\a\ExtractedFiles\Framework\MartinHatch.Azure.Functions.v1.Tests.dll' because Method 'get_DataRow' in type 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestContextImplementation' from assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
```

The tests all execute without any issues at all when running from either:

- Visual Studio 2022 Test Explorer
- Azure DevOps BUILD Pipeline

I have checked and checked, and the settings between the Build and Release pipelines are IDENTICAL. 

## Steps to reproduce
Create .NET Framework 4.8 "Microsoft Unit Test" project using 
- MSTest.TestFramework 2.2.8
- MSTest.TestAdapter 2.2.8

Create a release pipeline in Azure DevOps running Unit Tests

## Expected behavior
The unit tests run

## Actual behavior
It fails to detect any unit tests with the above error message

## Environment
Microsoft Unit Test project
.NET Framework 4.8
Azure DevOps RELEASE Pipeline
Pipeline agent running Windows-2019

This is the YAML of the Unit Test in DevOps

```
steps:
- task: VSTest@2
  displayName: 'Framework - Automated Integration Tests'
  inputs:
    testAssemblyVer2: |
     **\Framework\*.Tests.dll
     !**\obj\**
     !**\bin\**\ref\**
    runSettingsFile: '$(System.DefaultWorkingDirectory)/ExtractedFiles/Framework/Test Parameters/IntegrationSettings.runsettings'
    overrideTestrunParameters: '-BuildNumber "$(Build.BuildNumber)" -ReleaseNumber "$(Release.ReleaseName)" -Environment "Test"'
    runInParallel: false
    codeCoverageEnabled: false
  continueOnError: true
```
