### ISSUE TITLE
17.X breaks Fakes / Shims using VSTest behind proxy (missing Microsoft.IntelliTrace.ProfilerProxy.dll)

### ISSUE THREAD

**Issue by bejax** [microsoft/vstest#3404]
## Description
17.1 (also tested with 17.0 & 17.2 preview) breaks running UnitTest with Fakes / Shims using VSTest with a selfhosted agent behind a proxy.
Tests running just fine in 16.11.
Switching to 17.0 made the tests suddenly throw an exception UnitTestIsolationException: "Failed to get profiler module handle"

Found this PR and it seams related:
https://github.com/microsoft/vstest/pull/3068

From 17.0 and later the x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\ProfilerProxy files are missing.
Copying the folder manually to version 17.1 (from 16.11) fixes problem.

## Steps to reproduce
Unit test that includes:

```
using (ShimsContext.Create())
{
....
}

```
Running test using Azure Devops agent on prem with a pipeline:
```
 - task: VisualStudioTestPlatformInstaller@1
        inputs:
          packageFeedSelector: 'nugetOrg'
          versionSelector: 'latestStable'

  - task: VSTest@2
        displayName: 'IntegrationTests'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*IntegrationTests.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          vsTestVersion: 'toolsInstaller'
          testRunTitle: '$(Build.BuildNumber)-IntegrationTests-OnPrem'
```

Target framework: .NET Framework 4.8
DevOps Build Agent: Self hosted version 2.198.3

## Expected behavior
Expect tests to run just as fine with 17.0 and later as with 16.11

## Actual behavior
When the above test is running the code ShimsContext.Create() it fails with exception:
`2022-02-22T08:44:43.2312731Z   Error Message:
2022-02-22T08:44:43.2313421Z    Test method ABCD01.TestPlatform.IntegrationTests.AdditionTests.OnePlusTwoWithShim threw exception: 
2022-02-22T08:44:43.2314669Z Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException: Failed to get profiler module handle 'E:\App\SYSTAgents\COMPNAME01_Build_1\_work\_tool\VsTest\17.1.0\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\Microsoft.IntelliTrace.Profiler.dll'. The specified module could not be found ---> System.ComponentModel.Win32Exception: The specified module could not be found
2022-02-22T08:44:43.2315921Z   Stack Trace:
2022-02-22T08:44:43.2316435Z       at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.LibraryMethods.GetModuleHandle(String fileName)
2022-02-22T08:44:43.2317178Z    at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.LoadProfilerModule(String profilerPath)
2022-02-22T08:44:43.2317785Z --- End of inner exception stack trace ---
2022-02-22T08:44:43.2318375Z     at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.LoadProfilerModule(String profilerPath)
2022-02-22T08:44:43.2319109Z    at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.Initialize()
2022-02-22T08:44:43.2320124Z    at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationRuntime.InitializeUnitTestIsolationInstrumentationProvider()
2022-02-22T08:44:43.2320783Z    at Microsoft.QualityTools.Testing.Fakes.Shims.ShimRuntime.CreateContext()
2022-02-22T08:44:43.2321518Z    at ABCD01.TestPlatform.IntegrationTests.AdditionTests.OnePlusTwoWithShim() in D:\a\1\s\ABCD01.TestPlatform.IntegrationTests\AdditionTests.cs:line 21`

## Diagnostic logs
[FailingLog_17.1.0.txt](https://github.com/microsoft/vstest/files/8117334/FailingLog_17.1.0.txt)
[OkLog_16.11.0.txt](https://github.com/microsoft/vstest/files/8117335/OkLog_16.11.0.txt)

## Environment
Operating System: Windows Server 2019

##[debug]Generating list of args to pass to vstest.console.exe.
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
