### ISSUE TITLE
Code Coverage : RunSettings : Cobertura format is not working, even tough it works with CLI

### ISSUE THREAD

**Issue by p00j4** [microsoft/vstest#3497]
I'm trying VSTest task to use my runsettings and generate a Cobertura report, which works fine on my local CLI, however when same ran on ADO pipeline, generates .coverage file instead of *.cobertra.xml file 

**Steps to Reproduce**
1. Have a sample C++ project solution
2. Add runsetting 

**CodeCoverage.runsettings**
```

<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <DataCollectionRunSettings>
        
        <DataCollectors>
            <DataCollector friendlyName="Code Coverage">
                <Configuration>
                    <Format>Cobertura</Format>
                </Configuration>
            </DataCollector>
            
            
        </DataCollectors>
    </DataCollectionRunSettings>
</RunSettings>
```

3. Create a sample ADO pipeline with VSTest task 
**Task** 
```
      - task: VSTest@2
        displayName: Execute Unit Tests for $MySolution
        inputs:
          testAssemblyVer2: '**\*unittest*.dll'
          searchFolder: $(outputDirectory)  
          vsTestVersion: toolsInstaller
          runSettingsFile: Src\CodeCoverage.runsettings
          resultsFolder: '$(Agent.TempDirectory)\TestResults'
          diagnosticsEnabled: True
          codeCoverageEnabled: true
          collectDumpOn: Always
          testRunTitle: ""
          rerunFailedTests: true
          rerunMaxAttempts: 2
          condition: and(
                        succeeded() 
           )
```
4. Run it and observe, it generates dot coverage file. Instead is supposed to generate a cobertura file 

5. The same works using CLI 
**Cli run** 
vstest.console.exe MySolution.UnitTests.dll --EnableCodeCoverage --settings:$MyPath\Src\CodeCoverage.runsettings
![cmd_iTYSyi6tIZ](https://user-images.githubusercontent.com/6470509/159465153-7929f7ef-2a39-4769-98df-9851f063242c.png)

However, on ADO, the same config, generates a dot coverage file instead

![msedge_QenWERK0BI](https://user-images.githubusercontent.com/6470509/159466074-26302bb3-3b1b-44b2-a0c2-5ccea709b397.png)

**Debug info:**
The runsettings ADO has automatically modified to
![image](https://user-images.githubusercontent.com/6470509/159471478-a33331ac-7b3d-4ec7-9d1a-8adff970a018.png)

![image](https://user-images.githubusercontent.com/6470509/159471074-79ef236f-b3ae-4c0c-9234-f3519be5f1cb.png)

But update: If I modify the runsetting (as of the ADO) on my local and run with CLI, it still works fine. It's only not working with the ADO task. What am I missing?
