### ISSUE TITLE
Test execution takes a lot of time for very few tests at random with message 'Polling on remoteEndPoint'

### ISSUE THREAD

**Issue by aswinfrancis91** [microsoft/vstest#4153]
## Description
We have couple of builds that might run in parallel. All of them have dotnet test task. At time some of these tests take a lot of time to finish. For example we have an 'Inventory' project which has just 11 tests right now but it took 43mins. Another build was also running and it kept running the test task for close to an hour so I had to cancel it.
I see that when the delay happens the below log is seen continuously
`TpTrace Verbose: 0 : 12316, 10, 2022/11/25, 00:56:07.470, 26584036321527, vstest.console.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: 127.0.0.1:61798 localEndPoint: 127.0.0.1:61797
`
## Steps to reproduce
YAML
```
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test ${{ pair.name }}'
      inputs:
        command: test
        projects: '${{ parameters.projects }}'
        arguments: |
          --diag:log.txt --logger:"console;verbosity=detailed" --configuration ${{ parameters.configuration }} -p:DisableFody=true -p:DebugType=Full -f:${{ pair.name }} -p:CollectCoverage=${{ parameters.coverage }} -nodereuse:false --collect:"XPlat Code Coverage" --results-directory="$(Build.ArtifactStagingDirectory)/results"  --filter "${{ coalesce(parameters.filter,'DisplayName!=1All') }}" -p:CoverageRoot="$(Build.ArtifactStagingDirectory)/results" --results-directory "$(Build.ArtifactStagingDirectory)/results/${{ pair.name }}" --logger "trx;LogFileName=TestResults.trx" -p:RefProjVersion="${{ parameters.ProjectVersion }}" -p:RefProjMoniker="${{ parameters.RefProjMoniker }}"
        testRunTitle: '${{ parameters.title }} - ${{ pair.name }}'
        publishTestResults: false
```

## Expected behavior
Test should run/finish fast. Normally finishes in under 30 seconds

## Actual behavior
Take sa lot of time at times with below message
`TpTrace Verbose: 0 : 12316, 10, 2022/11/25, 00:56:07.470, 26584036321527, vstest.console.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: 127.0.0.1:61798 localEndPoint: 127.0.0.1:61797
`

## Diagnostic logs
[log.datacollector.22-11-25_00-50-35_71295_5.txt](https://github.com/microsoft/vstest/files/10120886/log.datacollector.22-11-25_00-50-35_71295_5.txt)
[log.host.22-11-25_00-50-36_86692_5.txt](https://github.com/microsoft/vstest/files/10120889/log.host.22-11-25_00-50-36_86692_5.txt)
[log.txt](https://github.com/microsoft/vstest/files/10120890/log.txt)
[Raw_Azure_Pipeline_log.txt](https://github.com/microsoft/vstest/files/10120924/Raw_Azure_Pipeline_log.txt)

## Environment
Build server: Windows Server 2019 Standard
Dotnet 5 project
Reference packages:
![image](https://user-images.githubusercontent.com/1233653/204742542-33df46b7-2137-4b04-b54a-5d2316af8bb8.png)
Build agent version: 2.211.1
