### ISSUE TITLE
Testhost process for source(s) '[...]/My.Library.UnitTests.dll' exited with error: Cannot open assembly '[...]/../TestHostNetFramework/testhost.net472.exe': No such file or directory

### ISSUE THREAD

**Issue by dhabierre** [microsoft/vstest#4295]
## Description

At present time I am  using Azure DevOps Pipeline with **VSTest@2** task to execute Unit Tests:

```yaml
- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testAssemblyVer2: |
     **\$(buildConfiguration)\*test*.dll
     !**\obj\**
    vstestLocationMethod: location
    vstestLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'
    runInParallel: false
    runTestsInIsolation: true
    codeCoverageEnabled: true
    publishRunAttachments: false
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```

My goal: trying to do this using **[Docker Mono](https://github.com/mono/docker)**.

## Steps to reproduce

```bash
docker pull mono:6.12.0.182
 
docker run -it --name mono-nuget -v C:\DEV\My.Library:/src mono:6.12.0.182

nuget restore "/src/My.Library.sln"
 
msbuild /p:Configuration="Release" /p:Platform="Any CPU" "/src/My.Library.sln" -m

cd /src/packages
 
nuget install Microsoft.TestPlatform -version 17.4.1
 
mono /src/packages/Microsoft.TestPlatform.17.4.1/tools/net462/Common7/IDE/Extensions/TestPlatform/vstest.console.exe "/src/**/bin/Release/*UnitTests*.dll" /InIsolation /Logger:"trx" /EnableCodeCoverage /ResultsDirectory:"/src/TestResults"
```

## Expected behavior

Succeeded operation.

## Actual behavior

```bash
root@58afa969d5ac:/src/packages# mono /src/packages/Microsoft.TestPlatform.17.4.1/tools/net462/Common7/IDE/Extensions/TestPlatform/vstest.console.exe "/src/Tests/UnitTests/My.Library.UnitTests/bin/Release/My.Library.UnitTests.dll" /Logger:"trx" /EnableCodeCoverage /ResultsDirectory:"/src/TestResults"
Microsoft (R) Test Execution Command Line Tool Version 17.4.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
0.5808
Testhost process for source(s) '/src/Tests/UnitTests/My.Library.UnitTests/bin/Release/My.Library.UnitTests.dll' exited with error: Cannot open assembly '/src/packages/Microsoft.TestPlatform.17.4.1/tools/net462/Common7/IDE/Extensions/TestPlatform/Extensions/../TestHostNetFramework/testhost.net472.exe': No such file or directory.
. Please check the diagnostic logs for more information.
Data collector 'Code Coverage' message: No code coverage data available. Profiler was not initialized. Verify that glibc (>=2.27), libxml2 and all .NET dependecies are installed..
Results File: /src/TestResults/_58afa969d5ac_2023-02-10_09_27_57.trx

Test Run Aborted.
```

💡 UnitTests project is written using .net 4.7.2

Any help is welcome :)
Thanks!
