### ISSUE TITLE
error TF298509 when running in Azure DevOps:

### ISSUE THREAD

**Issue by apobekiaris** [microsoft/vstest#4760]
```
##[error]Data collector 'Screen and Voice Recorder' message: Data collector caught an exception of type 'Microsoft.VisualStudio.TestTools.DataCollection.MediaRecorder.MediaRecorderException': 'Failed to establish communication with the screen recorder process'. More details: TF298509 : An error occurred while starting the screen recorder. Media will not be recorded. Review the log file for more details...

```

The exception is thrown everytime and on different agents regardless if the build succeeds.

Next is my yml and the used template
```xml
jobs:
  - job: ImportData
    displayName: 'ImportData Job'
    timeoutInMinutes: 90
    variables:
      defaultWorkingDir: '$(System.DefaultWorkingDirectory)\CS'
      runSettingsPath: '$(defaultWorkingDir)\Tests\Tests.runsettings'
      testsFolderPath: '$(defaultWorkingDir)\Tests'
      dxFeedVar: '$(DXFeed)'
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: PowerShell@2
      displayName: Build
      continueOnError: false
      inputs:
        targetType: 'inline'
        script: |
          & sqllocaldb start mssqllocaldb
          dotnet nuget add source $(dxFeedVar) --name DX
          cd "$(defaultWorkingDir)"
          dotnet build --configuration TEST
          Get-ChildItem -Path "$(testsFolderPath)" -Recurse -Directory -Include "ref", "refint", "obj" | 
          ForEach-Object { Remove-Item $_.FullName -Recurse -Force }  
        pwsh: true      
    - task: VSTest@3
      displayName: 'ImportData.Test'
      continueOnError: false
      enabled: true
      inputs:
        minimumExpectedTests: "1"
        failOnMinTestsNotRun: true
        searchFolder: $(testsFolderPath)
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\OutlookInspired.Win.Tests.dll'
        testFiltercriteria: TestCategory=ImportData
        diagnosticsEnabled: true
        codeCoverageEnabled: true
        runSettingsFile: $(runSettingsPath)

  - template: job-template.yml
    parameters:
      testAssembly: '**\OutlookInspired.Win.Tests.dll'
      displayName: 'Windows'
  
  - template: job-template.yml
    parameters:
      testAssembly: '**\OutlookInspired.Blazor.Tests.dll'
      displayName: 'Blazor'

``` 

```
parameters:
  testAssembly: ''
  displayName: ''

jobs:
- job: ${{ parameters.displayName }}
  variables:
    defaultWorkingDir: '$(System.DefaultWorkingDirectory)\CS'
    runSettingsPath: '$(defaultWorkingDir)\Tests\Tests.runsettings'
    testsFolderPath: '$(defaultWorkingDir)\Tests'
    dxFeedVar: '$(DXFeed)'
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  strategy:
    matrix:
      Admin: {}
      Sales: {}
      Support: {}
      Management: {}
      Engineering: {}
      IT: {}
      Shipping: {}
      HumanResources: {}
  timeoutInMinutes: 90
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: PowerShell@2
    displayName: Build
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        Write-Output "${{ parameters.testAssembly }}"
        & sqllocaldb start mssqllocaldb
        dotnet nuget add source $(dxFeedVar) --name DX
        cd "$(defaultWorkingDir)"
        dotnet build --configuration TEST
        Get-ChildItem -Path "$(testsFolderPath)" -Recurse -Directory -Include "ref", "refint", "obj" | 
        ForEach-Object { Remove-Item $_.FullName -Recurse -Force }  
      pwsh: true      
  - task: VSTest@3
    displayName: ${{ parameters.displayName }}
    continueOnError: false
    env:
        TEST_ROLE: $(Agent.JobName)
        BingKey: $(BingKey)
    enabled: true
    inputs:
      minimumExpectedTests: "1"
      failOnMinTestsNotRun: true
      rerunFailedTests: false
      searchFolder: $(testsFolderPath)
      testSelector: 'testAssemblies'
      testAssemblyVer2: ${{ parameters.testAssembly }}
      testFiltercriteria: TestCategory=Tests
      diagnosticsEnabled: true
      codeCoverageEnabled: true
      uiTests: true
      runSettingsFile: $(runSettingsPath)
      otherConsoleOptions: '/Diag:vstestlog.txt'
  - task: CopyFiles@2
    displayName: Copy vstestlog logs to staging
    inputs:
      contents: '**/*vstestlog*.txt'
      targetFolder: $(Build.ArtifactStagingDirectory)/vstestlog
    condition: always()
  - task: PublishPipelineArtifact@1
    displayName: Publish vstestlog log
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/vstestlog
      artifactName: vstestlog-$(Agent.JobName)-$(Build.BuildId)
    condition: always()


```
[vstestslog.zip](https://github.com/microsoft/vstest/files/13438865/vstestslog.zip)

attaching my logs
